# Generated by Django 3.2.6 on 2022-06-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankItemName', models.CharField(max_length=200)),
                ('itemAquiredOn', models.DateTimeField()),
                ('bankitemDescription', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('bankItemPrice', models.FloatField(help_text='The price of item when bought')),
            ],
        ),
    ]
